# Generated by Django 3.1 on 2023-04-02 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Penta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('course', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('phonenumber', models.CharField(max_length=50)),
                ('joindate', models.CharField(max_length=50)),
                ('response', models.CharField(max_length=50)),
                ('confirmation', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'enquriesform',
            },
        ),
        migrations.CreateModel(
            name='Primary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.CharField(max_length=50)),
                ('date', models.CharField(max_length=50)),
                ('fname', models.CharField(max_length=50)),
                ('school', models.CharField(max_length=50)),
                ('phonenumber', models.CharField(max_length=50)),
                ('response', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'studentinfo',
            },
        ),
        migrations.CreateModel(
            name='Secondary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseid', models.CharField(max_length=50)),
                ('coursename', models.CharField(max_length=50)),
                ('duration', models.CharField(max_length=50)),
                ('startdate', models.CharField(max_length=50)),
                ('enddate', models.CharField(max_length=50)),
                ('courseamount', models.CharField(max_length=50)),
                ('discount', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'courses',
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('date', models.CharField(max_length=50)),
                ('course', models.CharField(max_length=50)),
                ('time', models.CharField(max_length=50)),
                ('attendance', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'attendance',
            },
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('course', models.CharField(max_length=50)),
                ('feesamount', models.CharField(max_length=50)),
                ('feespaid', models.CharField(max_length=50)),
                ('feesdue', models.CharField(max_length=50)),
                ('paymentdate', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'feesinfo',
            },
        ),
        migrations.AlterField(
            model_name='member',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
